ALTER TABLE `event` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;
ALTER TABLE `session` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;
ALTER TABLE `handrecord` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;
ALTER TABLE `match` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;
ALTER TABLE `play` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;
ALTER TABLE `result` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;
ALTER TABLE `subscriber` ADD COLUMN createtimestamp TIMESTAMP default CURRENT_TIMESTAMP;